"""Update numeric precision

Revision ID: b40d498b8bf2
Revises: 2612abe9955d
Create Date: 2024-04-25 18:55:57.708006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b40d498b8bf2'
down_revision: Union[str, None] = '2612abe9955d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assets', 'sum',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=15, scale=6),
               existing_nullable=True)
    op.alter_column('calculations', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               type_=sa.Numeric(precision=16, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('calculations', 'total',
               existing_type=sa.Numeric(precision=16, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    op.alter_column('assets', 'sum',
               existing_type=sa.Numeric(precision=15, scale=6),
               type_=sa.NUMERIC(precision=10, scale=6),
               existing_nullable=True)
    # ### end Alembic commands ###
